import {
  project1Laptop,
  project1Mobile,
  project2Laptop,
  project2Mobile,
  project3Laptop,
  project3Mobile,
  project4Laptop,
  project4Mobile,
  project5Laptop,
  project5Mobile,
  project6Laptop,
  project6Mobile,
} from "./projectImages";

export const projectData = [
  {
    id: 1,
    image: project1Laptop,
    transitionImage: project1Mobile,
    title: "Corporate Website",
    technology:"React Js",
    hasLink: true,
    codeLink: "https://github.com/muruga1980/symbioticinfotech",
    liveLink: "https://symbioticinfotech.netlify.app/",
  },
  {
    id: 2,
    image: project2Laptop,
    transitionImage: project2Mobile,
    title: "E-Learning CMS",
    technology:"React Js",
    hasLink: false,
    codeLink: "",
    liveLink: "",
  },
  {
    id: 3,
    image: project3Laptop,
    transitionImage: project3Mobile,
    title: "Du-DigTv",
    technology:"React Js",
    hasLink: false,
    codeLink: "",
    liveLink: "",
  },
  {
    id: 4,
    image: project4Laptop,
    transitionImage: project4Mobile,
    title: "Portfolio",
    technology:"React Js",
    hasLink: true,
    codeLink: "https://github.com/monciego/coderig-landing-page",
    liveLink: "https://murugan-portfolio.netlify.app/",
  },
  {
    id: 5,
    image: project5Laptop,
    transitionImage: project5Mobile,
    title: "Sikth Matrimony",
    technology:"UI / UX",
    hasLink: true,
    codeLink: "",
    liveLink: "https://www.sikhmatrimony.com/",
  },
  {
    id: 6,
    image: project6Laptop,
    transitionImage: project6Mobile,
    title: "Mobile Tutor",
    technology:"UI / UX",
    hasLink: true,
    codeLink: "",
    liveLink: "https://www.m-tutor.com/",
  },
];
